services:
  postgres:
    image: postgres:latest
    container_name: postgres_f1_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: f1_analytics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pAssw0rd
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local